server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/item/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
