server:
  port: 8085

spring:
  application:
    name: config-server

#this is for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
