server:
  port: 8085

spring:
  application:
    name: config-server

#this is for config server to allocate where we put configuration on github - location
  cloud:
    config:
      server:
        git:
          uri: /media/sanu/MyComputer/LECTURES/All Notes/microservice/config


#this is for eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
