spring:
  application:
    name: registry
  config:
    import: optional:configserver:http://localhost:8085/

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
management:
  endpoints:
    web:
      exposure:
        exclude: "*"


